name: Lighthouse Audit on Vercel Preview

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  lighthouse:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Lighthouse
        run: npm install -g lighthouse
      - name: Check token presence (debug only, don't log real tokens in production)
        run: |
          if [ -z "${{ secrets.VERCEL_TOKEN }}" ]; then
            echo "❌ VERCEL_TOKEN is empty"
            exit 1
          else
            echo "✅ VERCEL_TOKEN is set"
          fi

      - name: Get Vercel Preview URL
        id: get-url
        run: |
          BRANCH_NAME="${GITHUB_HEAD_REF}"
          echo "Looking for deployment for branch: $BRANCH_NAME"

          DEPLOYMENTS=$(curl -s -H "Authorization: Bearer ${{ secrets.VERCEL_TOKEN }}" \
            "https://api.vercel.com/v6/deployments?projectId=${{ secrets.VERCEL_PROJECT_ID }}&meta-githubCommitRef=$BRANCH_NAME&limit=5")

          echo "Raw deployments:"
          echo "$DEPLOYMENTS"

          PREVIEW_URL=$(echo "$DEPLOYMENTS" | jq -r '.deployments[] | .url' | head -n 1)

          if [ -z "$PREVIEW_URL" ]; then
            echo "No preview deployment found."
            exit 1
          fi

          echo "preview_url=https://$PREVIEW_URL" >> $GITHUB_OUTPUT


      - name: Run Lighthouse
        run: |
          lighthouse "${{ steps.get-url.outputs.preview_url }}" \
            --output html \
            --output-path ./lighthouse-report.html \
            --quiet \
            --chrome-flags="--headless"

      - name: Upload Lighthouse Report
        uses: actions/upload-artifact@v4
        with:
          name: lighthouse-report
          path: ./lighthouse-report.html
